/**
 * `npm run cohort` reports the Salesforce cohort and what still needs work.
 *
 * Prints the table and regenerates `state/cohort.md`, the tracked human-readable
 * view. Everything here is DERIVED from state/world.json on the spot. Nothing
 * about asset completeness or Salesforce presence is stored in cohort.json, so
 * the two files cannot disagree.
 *
 *   npm run cohort                # full table
 *   npm run cohort -- --pending   # only members still needing generation
 */

import { loadWorld } from "../src/ledger/ledger.js";
import { loadCohort, memberStatuses, type MemberStatus } from "../src/cohort.js";
import { writeText, repoPath } from "../src/util/fs.js";
import { todayISO } from "../src/util/date.js";

const pendingOnly = process.argv.includes("--pending");

const world = loadWorld();
const cohort = loadCohort();

if (cohort.members.length === 0) {
  console.log("No cohort selected yet. Run `npm run cohort:select`.");
  process.exit(0);
}

const statuses = memberStatuses(world, cohort).sort((a, b) => a.oppId.localeCompare(b.oppId));
const shown = pendingOnly ? statuses.filter((s) => s.state !== "complete") : statuses;

const KINDS = ["call_transcript", "email_exchange", "ae_note", "survey", "interview"] as const;
const SHORT: Record<string, string> = {
  call_transcript: "transcripts",
  email_exchange: "emails",
  ae_note: "notes",
  survey: "survey",
  interview: "interview",
};

function assetCell(s: MemberStatus): string {
  if (s.total === 0) return "untouched";
  const parts: string[] = [];
  for (const k of KINDS) {
    const c = s.counts[k];
    if (!c) continue;
    parts.push(`${SHORT[k]} ${c.generated}${c.planned ? `+${c.planned}p` : ""}`);
  }
  return parts.join(" · ") || "-";
}

// --- console ----------------------------------------------------------------
const mix = { won: 0, lost: 0, open: 0 } as Record<string, number>;
const bySource = { seed: 0, weekly: 0 } as Record<string, number>;
let inSf = 0;
const stateCount = { untouched: 0, planned: 0, complete: 0 } as Record<string, number>;
for (const s of statuses) {
  mix[s.dealStatus] = (mix[s.dealStatus] ?? 0) + 1;
  bySource[s.source] = (bySource[s.source] ?? 0) + 1;
  if (s.inSalesforce) inSf++;
  stateCount[s.state] = (stateCount[s.state] ?? 0) + 1;
}
const closed = (mix.won ?? 0) + (mix.lost ?? 0);

console.log(`Salesforce cohort: ${cohort.members.length} of ${cohort.targetSize} target\n`);
console.log(
  `  outcome    won ${mix.won ?? 0} · lost ${mix.lost ?? 0} · open ${mix.open ?? 0}   (win rate ${closed ? ((100 * (mix.won ?? 0)) / closed).toFixed(1) : "0.0"}% of ${closed} closed)`,
);
console.log(
  `  source     seed ${bySource.seed ?? 0} (no Slack) · weekly ${bySource.weekly ?? 0} (full layer)`,
);
console.log(`  salesforce ${inSf} pushed · ${statuses.length - inSf} not yet`);
console.log(
  `  assets     ${stateCount.complete} complete · ${stateCount.planned} partly planned · ${stateCount.untouched} untouched\n`,
);

for (const s of shown) {
  const sf = s.inSalesforce ? "SF ✓" : "SF -";
  const flag = s.state === "complete" ? "" : s.state === "planned" ? `  ${s.planned} PLANNED` : "";
  console.log(
    `  ${s.oppId}  ${s.accountName.slice(0, 26).padEnd(26)} ${s.dealStatus.padEnd(5)} ${s.source.padEnd(6)} ${sf}  ${assetCell(s)}${flag}`,
  );
}
if (pendingOnly && shown.length === 0) console.log("  (every member is complete)");

// --- state/cohort.md --------------------------------------------------------
const rows = statuses
  .map(
    (s) =>
      `| ${s.oppId} | ${s.accountName} | ${s.dealStatus} | ${s.source} | ${s.inSalesforce ? "✓" : "-"} | ${assetCell(s)} | ${s.state} |`,
  )
  .join("\n");

writeText(
  repoPath("state", "cohort.md"),
  `# Salesforce cohort

Generated by \`npm run cohort\` on ${todayISO()}. Do not hand-edit. Membership is
owned by [\`state/cohort.json\`](cohort.json); every column right of \`source\` is
derived live from \`state/world.json\`.

**${cohort.members.length} of ${cohort.targetSize} target** · won ${mix.won ?? 0} / lost ${mix.lost ?? 0} / open ${mix.open ?? 0} · win rate ${closed ? ((100 * (mix.won ?? 0)) / closed).toFixed(1) : "0.0"}% of ${closed} closed
**Source** seed ${bySource.seed ?? 0} (transcripts + emails always, notes/win-loss occasional, no Slack) · weekly ${bySource.weekly ?? 0} (full layer incl. Slack)
**Assets** ${stateCount.complete} complete · ${stateCount.planned} partly planned · ${stateCount.untouched} untouched
**Salesforce** ${inSf} pushed · ${statuses.length - inSf} not yet

| Opp | Account | Outcome | Source | SF | Assets | State |
| --- | --- | --- | --- | --- | --- | --- |
${rows}
`,
);
console.log(`\n✓ state/cohort.md regenerated.`);
